In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline

In [5]:
df = pd.read_csv('../data/ch4_scores400.csv')
scores = np.array(df['score'])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80])

In [7]:
a=np.array(scores)
np.shape(a)

(400,)

In [9]:
np.random.choice([1,2,3],3)

array([2, 1, 3])

In [14]:
np.random.choice([1,2,3],3, replace=False)

array([1, 3, 2])

In [17]:
np.random.seed(0)
sample=np.random.choice(scores, 20)
sample.mean()

70.4

In [18]:
scores.mean()

69.53

In [19]:
for i in range(5):
    sample = np.random.choice(scores, 20)
    print(f'{i+1}번째 무작위추출로 얻은 표본평균', sample.mean())

1번째 무작위추출로 얻은 표본평균 72.45
2번째 무작위추출로 얻은 표본평균 63.7
3번째 무작위추출로 얻은 표본평균 66.05
4번째 무작위추출로 얻은 표본평균 71.7
5번째 무작위추출로 얻은 표본평균 74.15
