In [37]:
# ### 붓꽃의 4가지 속성(피처 (Feature))
# - 꽃받침 길이 : Sepal Length
# - 꽃받침 너비 : Sepal Width
# - 꽃잎의 길이 : Petal Length
# - 꽃잎의 너비 : Petal Width

In [38]:
# ### 분류를 위한 학습 및 예측 프로세스
# 
# - 0단계. 데이터 세트 준비
#     - 데이터 세트 로딩, 데이터 프레임으로 변환
# 
# 
# - 1단계. 데이터 세트 분리
#     - 데이터를 학습 데이터와 테스트 데이터로 분리
# 
# 
# - 2단계. 모델 학습
#     - 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델 학습
# 
# 
# - 3단계. 예측 수행
#     - 학습된 ML 모델을 이용해 테스트 데이터의 분류(붓꽃 종류) 예측
# 
# 
# - 4단계. 모델 성능 평가
#     - 예측된 결과값과 테스트 데이터 실제 값 비교하여 ML 모델 성능 평가
# 

In [39]:
# 용어 정리
# 
# 피처(Feature) : 데이터 세트 속성
# - feature_names : sepal length, sepal with, petal length, petal width
#     
# 레이블(label) :
# - 품종 (setosa, versicolor, virginica)
# - 학습 : 결정값(주어진 정답)
# - 테스트 : 타깃값(target)(예측해야 할 값)
# - target(숫자) : 0, 1, 2
# - target_names : setosa, versicolor, virginica
# - 레이블 = 결정값 = 타겟값


In [40]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [41]:
# 데이터 세팅 로드
import pandas as pd

In [42]:
# iris.data : Iris 데이터 세트에서 
# 피처(feature)만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data
print(iris_data[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [43]:
# iris.target은 붓꽃 데이터 세트에서 
# 레이블(결정 값) 데이터를 numpy로 가지고 있음 (숫자)
# 레이블 = 결정값 = 정답(품종을 숫자로 표현)
iris_label = iris.target
print(iris_label)
print(iris.target_names)
print(iris.feature_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [44]:
# 붓꽃 데이터 데이터프레임으로 변환
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [45]:
iris_df2 = iris_df
iris_df2.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [46]:
def label_name(label):
    if label == 0:
        name =='setosa'
    elif lable ==1:
        name == 'versicolor'
    else :
        name = 'virginica'
        
    return name

In [47]:
iris_df2['label_name']=iris_df2.apply(lambda x: label_name(x['label']), axis=1)

UnboundLocalError: local variable 'name' referenced before assignment

In [49]:
#학습 데이터와 테스트 데이터 세트로 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.3, random_state=11)


In [50]:
# 학습용 피처 데이터 세트
X_train[:10]

array([[5.1, 2.5, 3. , 1.1],
       [6.6, 2.9, 4.6, 1.3],
       [5. , 3.2, 1.2, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.8, 1.6, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5.9, 3. , 4.2, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.7, 3.1, 4.7, 1.5]])

In [51]:
# 테스트용 피처 데이터 세트
X_test[:10]



array([[6.8, 3. , 5.5, 2.1],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.4, 2.7, 5.3, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 4.4, 1.5, 0.4],
       [4.8, 3.1, 1.6, 0.2],
       [6.1, 2.9, 4.7, 1.4]])

In [52]:

# 학습용 레이블 데이터 세트
y_train[:10]

array([1, 1, 0, 2, 0, 2, 2, 1, 2, 1])

In [53]:
# 테스트용 레이블 데이터 세트
y_test[:10]

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1])

In [54]:
# DecisionTreeClassifier 객체 생성 
dt_clf = DecisionTreeClassifier(random_state=11)


In [55]:
# 학습 수행 
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [56]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행. 
pred = dt_clf.predict(X_test)

In [57]:
# # 사이킷런 기반 프레임워크 익히기

# ## Estimator 클래스
# - 머신러닝 모델(알고리즘) 클래스
# 
# 
# - 학습을 위해서 fit()을 학습된 모델의 예측을 위해 predict()메서드를 제공
#     - Estimator를 인자로 받는 함수는 Estimator의 fit()과 predict()를 호출해서 평가하거나 하이퍼파라미터 튜닝 수행
#     - 평가함수 cross_val_score()
#     - 하이퍼파라미터 튜닝 지원 클래스 GridSearchCV :  GridSearchCV.fit()
#     
# 
# **지도학습**
# 
# ![image.png](attachment:image.png)
# 
# 
# 
# **비지도학습**
# 
# - 차원축소, 클러스터링, 피처 추출 등을 구현한 클래스의 대부분이 fit()과 transform()을 적용
#     - 피처 추출에서 fit()은 지도학습의 fit()과 같은 학습이 아니라 입력 데이터 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업
#     - fit()으로 변환을 위한 사전구조를 맞추면 이후 입력 데이터의 차원 변환, 클러스터링, 피처 추출 등의 실제 작업은 transform()으로 수행함

In [ ]:
# ### 사이킷런의 내장 데이터 세트 구성과 의미

In [58]:
from sklearn.datasets import load_iris

In [59]:
iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [60]:
keys = iris_data.keys()
print(keys)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [61]:
# data
print("data type", type(iris_data.data))
print("data shape", iris_data.data.shape)
print(iris_data['data'])


data type <class 'numpy.ndarray'>
data shape (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0

In [62]:
# target
print("target type", type(iris_data.target))
print("target shape", iris_data.target.shape)
print(iris_data['target'])

target type <class 'numpy.ndarray'>
target shape (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [63]:
# target_names
print("target_names type", type(iris_data.target_names))
print("target_names shape", len(iris_data.target_names))
print(iris_data.target_names)

target_names type <class 'numpy.ndarray'>
target_names shape 3
['setosa' 'versicolor' 'virginica']


In [64]:
# feature_names
print("featuret_names type", type(iris_data.feature_names))
print("feature_names shape", len(iris_data.feature_names))
print(iris_data.feature_names)


featuret_names type <class 'list'>
feature_names shape 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [65]:
iris_data.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =